---

- hosts: all
  become: true
  tasks:


  - name: update repository index in Ubuntu 10.126.75.1 Popos 10.126.75.0 Debian 10.126.74.185
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian" 

  - name: install apache2 pachage in Ubuntu 10.126.75.1 Popos 10.126.75.0 Debian 10.126.74.185
    apt:
      name: apache2
      state: latest 
    when: ansible_os_family == "Debian"

  
  - name: add php support for apache in Ubuntu 10.126.75.1 Popos 10.126.75.0 Debian 10.126.74.185
    apt: 
      name: libapache2-mod-php
      state: latest
    when: ansible_os_family == "Debian"

  
  - name: Install TeamViewer QS on Ubuntu 10.126.75.1 Popos 10.126.75.0 Debian 10.126.74.185
    apt:
      deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
  

  - name: update repository index in fedora 10.126.74.148
    dnf:
      update_cache: yes
    when: ansible_os_family == "RedHat"

  - name: install apache2 pachage in fedora  10.126.74.148
    dnf:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: add php support for apache in fedora 10.126.74.148
    dnf:
      name: php
      state: latest
    when: ansible_os_family == "RedHat"





  - name: update repository index in Endeavour 10.126.74.29 Garuda 10.126.75.2 Manjaro 10.126.74.194
    pacman:
      update_cache: yes
    when: ansible_os_family == "Archlinux"

  - name: install apache2 pachage in Endeavour 10.126.74.29 Garuda 10.126.75.2 Manjaro 10.126.74.194
    pacman:
      name: apache
      state: latest
    when: ansible_os_family == "Archlinux"

  - name: add php support for apache in Endeavour 10.126.74.29 Garuda 10.126.75.2 Manjaro 10.126.74.194
    pacman:
      name: php
      state: latest
    when: ansible_os_family == "Archlinux"

