---

- hosts: all
  become: true
  tasks:


#  - name: update repository index
#    apt:
#      update_cache: yes
#    when: ansible_distribution_version == "Ubuntu"
   

  - name: install apache  and php packages Ubuntu package 
    apt:
      name: 
        - apache2
        - libapache2-mod-php 
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages ArchLinux package
    pacman:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Arch Linux"


 
#  - name: install apache and php packages ArchLinux  package
#  - name: install apache and php
#    package:
#      name: 
#        - "{{ apache_package }}"
#        - "{{ php_package }}"
#      state: latest
#      update_cache: yes 
#    when: ansible_distribution == "Archlinux"

  
