---

- hosts: all
  become: true
  tasks:


  - name: update repository index in ubuntu distros
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 

  - name: install apache2 pachage in ubuntu distro
    apt:
      name: apache2
      state: latest 
    when: ansible_distribution == "Ubuntu"

  
  - name: add php support for apache in ubuntu distros
    apt: 
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
 
    

  
  - name: update repository index in fedora
    dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install apache2 pachage
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Fedora"

  - name: add php support for apache in fedora
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "Fedora"
