---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Arch Linux)
    tags: always
    pacman:   
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Arch Linux"
  
  - name: install update (Ubuntu)
    tags: always
    apt:
      update: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

 

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu 
    apt:
      name: 
        - apache2
        - libapache2-mod-php 
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages archlinux servers
    tags: apache,Arch Linux,httpd
    pacman:
      name:
        - apache
        - php
      state: latest
    when: ansible_distribution == "Arch Linux"

- hosts: db_servers
  become: true 
  tasks:
  
  - name: install mariadb package (Arch Linux)
    tags: ArchLinux,db,mariadb
    pacman:
      name: mariadb
      state: latest
    when: ansible_distribution == "Arch Linux"
 
  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest



  
